name: garmian_house_of_charity
description: "پرۆژەیەکی تاکەکەسی تایبەت گەشەپێدراوە بۆ ڕێکخراوی ماڵێ خێرخوازان و هەژارانی گەرمیان "
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  syncfusion_flutter_core: ^27.2.3
  syncfusion_flutter_datagrid: ^27.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1 
  


flutter:
  uses-material-design: true
  assets:
      - assets/mylogo.jpg
  fonts:
    - family: DroidArabic
      fonts:
        - asset: assets/fonts/droid.ttf
  
flutter_icons:
android: true
ios: true
image_path_android: assets/mylogo.jpg
image_path_ios: assets/mylogo.jpg